class ErrorCodes:
     # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    UNAUTHORIZED="UNAUTHORIZED"
    USER_FORBIDDEN="FORBIDDEN"
    INVALID_USER="INVALID_USER"
    
    # Wallet
    WALLET_NOT_FOUND = "WALLET_NOT_FOUND"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    SAME_WALLET = "SAME_WALLET"

    # Transaction / Payment
    TRANSACTION_FAILED = "TRANSACTION_FAILED"
    TRANSACTION_REVERSED = "TRANSACTION_REVERSED"