# app/config/constants.py

CBC_PARAMS = [
    "HAEMOGLOBIN",
    "HAEMATOCRIT(PCV)",
    "RBC COUNT",
    "WBC COUNT",
    "PLATELET COUNT",
    "MEAN CELL VOLUME (MCV)",
    "MEAN CELL HAEMOGLOBIN (MCH)",
    "MEAN CELL HAEMOGLOBIN CONCENTRATION (MCHC)",
    "RDW - CV",
    "POLYMORPHS",
    "LYMPHOCYTES",
    "EOSINOPHILS",
    "MONOCYTES"
]

TEST_NAMES = [
    "COMPLETE BLOOD COUNT",
    "COMPLETE BLOOD PICTURE",
    "COMPLETE URINE EXAMINATION",
    "BLOOD CULTURE & SENSITIVITY",
    "URINE CULTURE & SENSITIVITY (CATHETER CATCH)",
    "CREATININE",
    "ELECTROLYTES",
    "BLOOD UREA",
    "LIVER FUNCTION TEST WITH PROTEINS",
    "PRO CALCITONIN",
    "ARTERIAL BLOOD GASES (ABG)",
    "SERUM ALBUMIN",
    "FLUID CULTURE & SENSITIVITY",
    "TACROLIMUS -",
    "X-RAY",
    "BRONCHIAL WASH-FUNGAL STAIN",
    "BRONCHIAL WASH-GRAMS STAIN",
    "GENE-XPERT",
    "MAGNESIUM",
    "PHOSPHOROUS",
    "CALCIUM",
    "POST LUNCH PLASMA SUGAR",
    "URIC ACID",
    "ESR",
    "VDRL",
    "HBsAg",
    "HCV",
    "HIV 1 & 2 Antibody tes",
    "ANTI HEPATITS B CORE ANTIGEN-IGM",
    "ANTI HEPATITIS B SURFACE ANTIBODIES",
    "PROTHROMBIN TIME[PT]",
    "ACTIVATED PARTIAL THROMBOPLASTIN TIME",
    "GLYCOSYLATED HAEMOGLOBIN (HBA1C)",
    "LIPID PROFILE",
    "FASTING PLASMA SUGAR",
    "THYROID PROFILE",
    "BLOOD GROUPING AND RH",
    "EPSTEIN BARR VIRUS SEROLOGY",
    "CMV QUANTITATIVE",
    "PRE ALBUMIN",
    "SINGLE ANTIGEN BEAD PANEL",
    "TB QUANTIFERRON",
    "PUS CULTURE & SENSITIVITY",
    "BEDSIDE ULTRASOUND",
    "BEDSIDE CAROTID DOPPLER / NECK VESSELS",
    "U/S UPPER/LOWER LIMB ARTERIAL BOTH LIMBS"
]

# Supported file types
ALLOWED_FILE_TYPES = ["pdf"]

# Directory where uploaded files will be stored
UPLOAD_DIR = "uploads"
